[package]
name = "wordle_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
progress_bar = "1.0.5"
text_io = "0.1.12"
rayon = "1.8.0"
